name: Check Attendance

on:
  workflow_dispatch:
  schedule:
    - cron: '35 4 * * 1-5'
    - cron: '15 6 * * 1-5'
    - cron: '05 7 * * 1-5'
    - cron: '05 8 * * 1-5'
    - cron: '55 8 * * 1-5'
    - cron: '45 9 * * 1-5'
    - cron: '34 10 * * 1-5'
    - cron: '25 11 * * 1-5'
    - cron: '*/30 * * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests schedule

      - name: Run script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python cyber.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add attendance_state.json
          git diff --staged --quiet || (git commit -m "Update attendance state" && git push)
